env = "dev"
rust_log = "rust_gcp=debug,tower_http::trace=debug"
google_cloud_project = "getcloudy-469014"
gae_service = "rust-gcp"
port = 8080
redishost = "10.207.177.140"
redisport = 6379

[pubsub]
max_messages = 10
max_bytes = 1024
max_latency = 5